export const PATH_ADMIN_DASHBOARD = 'PATH_ADMIN_DASHBOARD';
export const PATH_ADMIN_TASKBOARD = 'PATH_ADMIN_TASKBOARD';
export const PATH_USER_LOGIN = 'PATH_USER_LOGIN';
export const PATH_USER_REGISTER = 'PATH_USER_REGISTER';
