// Action Type
export const FETCH_TASK = 'FETCH_TASK';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const FETCH_TASK_FAILED = 'FETCH_TASK_FAILED';
export const FILTER_TASK = 'FILTER_TASK';
export const FILTER_TASK_SUCCESS = 'FILTER_TASK_SUCCESS';
export const ADD_TASK = 'ADD_TASK';
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED';
export const ADD_TASK_SUCCESSED = 'ADD_TASK_SUCCESSED';
export const ON_DELETE = 'ON_DELETE';
export const ON_DELETE_SUCCESSED = 'ON_DELETE_SUCCESSED';
export const ON_DELETE_FAILED = 'ON_DELETE_FAILED';
export const TASK_EDITTING = 'TASK_EDITTING';
export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_SUCCESSED = 'UPDATE_TASK_SUCCESSED';
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED';
